name: kaggle-tf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.6
  - pandas=1.3.5
  - matplotlib
  - scikit-learn
  - jupyterlab
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip
  - pip:
      - tensorflow-gpu==2.10.0
      - tensorflow-datasets
      - keras
      - opencv-python
      - pillow
      - seaborn
